repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml
  #- repo: https://github.com/psf/black
  #  rev: 22.10.0
  #  hooks:
  #    - id: black
  #      args: [ --line-length=100 ]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.3
    hooks:
      # Run the linter.
      - id: ruff
        args:
        - --config
        - ruff.toml
        - --fix
      # Run the formatter.
      - id: ruff-format
